### ISSUE TITLE
attachment_s3 : Module 'odoo.modules.registry' has no attribute 'RegistryManager'

### ISSUE THREAD

**Issue by StephaneMangin** [camptocamp/odoo-cloud-platform#194]
Here comes the output (https://caas.camptocamp.com/env/1a233618/apps/stacks/1st38499/services/1s211023/containers):
```bash
24/08/2020 11:23:07{"asctime": "2020-08-24 09:23:07,621", "pid": 222, "levelname": "WARNING", "dbname": "winter_sunset_3601_integration_13", "name": "odoo.modules.loading", "message": "Transient module states were reset", "perf_info": ""}
24/08/2020 11:23:07{"asctime": "2020-08-24 09:23:07,625", "pid": 222, "levelname": "ERROR", "dbname": "winter_sunset_3601_integration_13", "name": "odoo.modules.registry", "message": "Failed to load registry", "exc_info": "Traceback (most recent call last):\n  File \"/odoo/src/odoo/modules/registry.py\", line 86, in new\n    odoo.modules.load_modules(registry._db, force_demo, status, update_module)\n  File \"/odoo/src/odoo/modules/loading.py\", line 419, in load_modules\n    force, status, report, loaded_modules, update_module, models_to_check)\n  File \"/odoo/src/odoo/modules/loading.py\", line 315, in load_marked_modules\n    perform_checks=perform_checks, models_to_check=models_to_check\n  File \"/odoo/src/odoo/modules/loading.py\", line 230, in load_module_graph\n    migrations.migrate_module(package, 'post')\n  File \"/odoo/src/odoo/modules/migration.py\", line 180, in migrate_module\n    migrate(self.cr, installed_version)\n  File \"/odoo/external-src/odoo-cloud-platform/attachment_s3/migrations/13.0.0.0.1/post-migration.py\", line 26, in migrate\n    registry = odoo.modules.registry.RegistryManager.get(cr.dbname)\nAttributeError: module 'odoo.modules.registry' has no attribute 'RegistryManager'", "perf_info": ""}
24/08/2020 11:23:07{"asctime": "2020-08-24 09:23:07,627", "pid": 222, "levelname": "CRITICAL", "dbname": "winter_sunset_3601_integration_13", "name": "odoo.service.server", "message": "Failed to initialize database `winter_sunset_3601_integration_13`.", "exc_info": "Traceback (most recent call last):\n  File \"/odoo/src/odoo/service/server.py\", line 1190, in preload_registries\n    registry = Registry.new(dbname, update_module=update_module)\n  File \"/odoo/src/odoo/modules/registry.py\", line 86, in new\n    odoo.modules.load_modules(registry._db, force_demo, status, update_module)\n  File \"/odoo/src/odoo/modules/loading.py\", line 419, in load_modules\n    force, status, report, loaded_modules, update_module, models_to_check)\n  File \"/odoo/src/odoo/modules/loading.py\", line 315, in load_marked_modules\n    perform_checks=perform_checks, models_to_check=models_to_check\n  File \"/odoo/src/odoo/modules/loading.py\", line 230, in load_module_graph\n    migrations.migrate_module(package, 'post')\n  File \"/odoo/src/odoo/modules/migration.py\", line 180, in migrate_module\n    migrate(self.cr, installed_version)\n  File \"/odoo/external-src/odoo-cloud-platform/attachment_s3/migrations/13.0.0.0.1/post-migration.py\", line 26, in migrate\n    registry = odoo.modules.registry.RegistryManager.get(cr.dbname)\nAttributeError: module 'odoo.modules.registry' has no attribute 'RegistryManager'", "perf_info": ""}
24/08/2020 11:23:07{"asctime": "2020-08-24 09:23:07,633", "pid": 222, "levelname": "INFO", "dbname": "winter_sunset_3601_integration_13", "name": "odoo.service.server", "message": "Initiating shutdown", "perf_info": ""}
24/08/2020 11:23:07{"asctime": "2020-08-24 09:23:07,634", "pid": 222, "levelname": "INFO", "dbname": "winter_sunset_3601_integration_13", "name": "odoo.service.server", "message": "Hit CTRL-C again or send a second signal to force the shutdown.", "perf_info": ""}
24/08/2020 11:23:08Traceback (most recent call last):
24/08/2020 11:23:08  File "/usr/local/bin/marabunta", line 8, in <module>
24/08/2020 11:23:08    sys.exit(main())
24/08/2020 11:23:08  File "/usr/local/lib/python3.7/dist-packages/marabunta/core.py", line 154, in main
24/08/2020 11:23:08    migrate(config)
24/08/2020 11:23:08  File "/usr/local/lib/python3.7/dist-packages/marabunta/core.py", line 143, in migrate
24/08/2020 11:23:08    runner.perform()
24/08/2020 11:23:08  File "/usr/local/lib/python3.7/dist-packages/marabunta/runner.py", line 115, in perform
24/08/2020 11:23:08    VersionRunner(self, version).perform()
24/08/2020 11:23:08  File "/usr/local/lib/python3.7/dist-packages/marabunta/runner.py", line 169, in perform
24/08/2020 11:23:08    self._perform_version(version)
24/08/2020 11:23:08  File "/usr/local/lib/python3.7/dist-packages/marabunta/runner.py", line 200, in _perform_version
24/08/2020 11:23:08    self.perform_addons()
24/08/2020 11:23:08  File "/usr/local/lib/python3.7/dist-packages/marabunta/runner.py", line 226, in perform_addons
24/08/2020 11:23:08    operation.execute(self.log)
24/08/2020 11:23:08  File "/usr/local/lib/python3.7/dist-packages/marabunta/model.py", line 363, in execute
24/08/2020 11:23:08    self._execute(log, interactive=sys.stdout.isatty())
24/08/2020 11:23:08  File "/usr/local/lib/python3.7/dist-packages/marabunta/model.py", line 352, in _execute
24/08/2020 11:23:08    child.exitstatus
24/08/2020 11:23:08marabunta.exception.OperationError: command 'odoo --workers=0 --stop-after-init --no-xmlrpc -i account_plaid,account_invoice_extract_purchase,account_yodlee,account_ponto,camptocamp_website_tools,mass_editing,account_bank_statement_import_csv,base_import_async,barcodes_mobile,l10n_generic_auto_transfer_demo,website_sale_delivery,account_online_sync,account_bank_statement_import_camt -u analytic,website_google_map,web,website_forum,hr_contract,portal,quality_control,database_cleanup,http_routing,website_event_track,mass_mailing_resend,website_event_questions,hr_contract_sign,website,website_event,account,website_blog,website_mail_channel,monitoring_status,report_xlsx,base_technical_features,im_livechat_enterprise,website_helpdesk_form,monitoring_statsd,website_helpdesk_livechat,hr_recruitment_survey,website_sale_slides,base_location,google_account,auditlog,base_geolocalize,hr_expense,crm_livechat,account_financial_report,server_environment_files,cloud_platform,base_automation,website_sale_product_configurator,account_intrastat,website_hr_recruitment,helpdesk,base_iban,l10n_multilang,quality_mrp,barcodes,mail_environment,crm,stock_split_picking,attachment_s3,web_environment_ribbon,product,odoo_referral_portal,hr_attendance,contacts,website_partner,stock_barcode,mass_mailing_partner,hr_work_entry,date_range,logging_json,quality_mrp_workorder,purchase_mrp_workorder_quality,server_environment_ir_config_parameter,website_crm_partner_assign,website_livechat,event,sale_order_type,rating,project,mis_builder,purchase,account_budget,sales_team,link_tracker,utm,website_crm_livechat,l10n_generic_coa,bus,website_payment,hr_holidays,quality,gamification,calendar,phone_validation,website_helpdesk,fleet,sale_product_configurator,partner_firstname,website_sale,im_livechat_mail_bot,hr_timesheet,website_sale_product_attribute_value_filter_existing,mail,website_sale_stock_product_configurator,hr,mass_mailing,mis_builder_budget,resource,note,auth_ldap,website_form,im_livechat,sale,stock_dropshipping,l10n_ch_states,website_slides,hr_recruitment,account_analytic_default,account_asset,helpdesk_timesheet,partner_fax,stock,website_customer,base_address_city,sale_management,project_task_default_stage,board,hr_appraisal,l10n_ch,theme_default,product_state,base,product_dimension,mrp,survey,website_sale_comparison,cloud_platform_exoscale,sign,hr_org_chart,ocn_client,account_accountant,stock_intrastat,session_redis,delivery,server_environment,mrp_workorder,base_sparse_field' returned 255```

**Comment by guewen** [comment]
Here's the culprit: https://github.com/camptocamp/odoo-cloud-platform/blob/298050ba520e8becd1e1ef1dea5f127979ac3795/attachment_s3/migrations/13.0.0.0.1/post-migration.py#L26

**Comment by StephaneMangin** [comment]
Apparently the right class name would be Registry alone :

registry = odoo.modules.registry.Registry.get(cr.dbname)

**Comment by StephaneMangin** [comment]
Accidentaly closed
