### ISSUE TITLE
monitoring_log_requests: TypeError: _dispatch() missing 1 required positional argument: 'self'

### ISSUE THREAD

**Issue by foutoucour** [camptocamp/odoo-cloud-platform#43]
Hello guys,

I wanted to give a try to the module `monitoring_log_requests` but I have an error when I launch the instance.
Did you already see this error? I have the feeling I miss a setup. Where should I take a look?

``` python 
odoo_1  | Traceback (most recent call last):
odoo_1  |   File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 205, in run_wsgi
odoo_1  |     execute(self.server.app)
odoo_1  |   File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 193, in execute
odoo_1  |     application_iter = app(environ, start_response)
odoo_1  |   File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 166, in application
odoo_1  |     return application_unproxied(environ, start_response)
odoo_1  |   File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 154, in application_unproxied
odoo_1  |     result = handler(environ, start_response)
odoo_1  |   File "/usr/lib/python3/dist-packages/odoo/http.py", line 1318, in __call__
odoo_1  |     return self.dispatch(environ, start_response)
odoo_1  |   File "/usr/lib/python3/dist-packages/odoo/http.py", line 1292, in __call__
odoo_1  |     return self.app(environ, start_wrapped)
odoo_1  |   File "/usr/lib/python3/dist-packages/werkzeug/wsgi.py", line 599, in __call__
odoo_1  |     return self.app(environ, start_response)
odoo_1  |   File "/usr/lib/python3/dist-packages/odoo/http.py", line 1490, in dispatch
odoo_1  |     result = ir_http._dispatch()
odoo_1  |   File "/usr/lib/python3/dist-packages/odoo/addons/auth_signup/models/ir_http.py", line 19, in _dispatch
odoo_1  |     return super(Http, cls)._dispatch()
odoo_1  |   File "/usr/lib/python3/dist-packages/odoo/addons/web_editor/models/ir_http.py", line 22, in _dispatch
odoo_1  |     return super(IrHttp, cls)._dispatch()
odoo_1  | TypeError: _dispatch() missing 1 required positional argument: 'self'
```

**Comment by guewen** [comment]
:astonished: :dizzy_face: 

We don't use this module anymore, so it's seems its migration had been done a bit too blindy...

the _dispatch method is now a classmethod

```
    @classmethod
    def _dispatch(cls):
```

**Comment by foutoucour** [comment]
Oki!

I will work on this then.
As you don't use this module anymore, could you let me know what do you use now?
I want to get log in my kibana ;)

Cheers,
Jordi

**Comment by guewen** [comment]
We use the nginx stats for the basics with this [json log format](https://github.com/camptocamp/docker-odoo-nginx/blob/master/9.0/templates/nginx.conf.tmpl#L23) so we can parse it for kibana.

For the timing by method, we use grafana through a statsd gateway using
https://github.com/camptocamp/odoo-cloud-platform/tree/11.0/monitoring_statsd

**Comment by foutoucour** [comment]
Thanks for sharing @guewen !
